 <div class="field">
      <select name="field[<?=$fkey?>][validation][]" class="sixty custom-select">
        <option value=""><?=__('None','kontrolwp')?></option>
        <option value="validate-email" <?=(isset($data) && $data == 'validate-email') ? 'selected="selected"':'' ?>><?=__('Email Address','kontrolwp')?></option>
        <option value="<?=(isset($data) && strpos($data, 'validate-date') !== FALSE) ? $data:'' ?>" <?=(isset($data) && strpos($data, 'validate-date') !== FALSE) ? 'selected="selected"':'' ?> class="custom-val" customValFormat="validate-date dateFormat:'%s'" customLabelFormat="<?=__('Date','kontrolwp')?> - '%s'" confirmText="<?=__('Enter the format of the date','kontrolwp')?>:" confirmDefaultVal="%d/%m/%Y"><?=__('Date','kontrolwp')?> <?=(isset($data) && strpos($data, 'validate-date') !== FALSE) ? '- '.substr($data, 25, strlen($data)):'' ?></option>
        <option value="validate-numeric" <?=(isset($data) && $data == 'validate-numeric') ? 'selected="selected"':'' ?>><?=__('Numeric','kontrolwp')?> (1, 1.1, -1 etc.)</option>
        <option value="validate-integer" <?=(isset($data) && $data == 'validate-integer') ? 'selected="selected"':'' ?>><?=__('Integer','kontrolwp')?> (1, 2, 3 etc.)</option>
        <option value="validate-digits" <?=(isset($data) && $data == 'validate-digits') ? 'selected="selected"':'' ?>><?=__('Digits (contains spaces, numbers eg. a phone number)','kontrolwp')?></option>
        <option value="validate-alpha" <?=(isset($data) && $data == 'validate-alpha') ? 'selected="selected"':'' ?>><?=__('Alpha (contains only letters)','kontrolwp')?></option>
        <option value="validate-alphanum" <?=(isset($data) && $data == 'validate-alphanum') ? 'selected="selected"':'' ?>><?=__('Alphanumeric (contains only letters and numbers)','kontrolwp')?></option>
        <option value="validate-url" <?=(isset($data) && $data == 'validate-url') ? 'selected="selected"':'' ?>><?=__('URL (url address','kontrolwp')?> eg. www.kontrolwp.com)</option>
        <option value="<?=(isset($data) && strpos($data, 'length:') !== FALSE) ? $data:'' ?>" <?=(isset($data) && strpos($data, 'length:') !== FALSE) ? 'selected="selected"':'' ?> class="custom-val" customValFormat="length:%s" customLabelFormat="<?=__('Length','kontrolwp')?> (%s <?=__('characters','kontrolwp')?>)" confirmText="<?=__('Enter the character length required for this field: eg. 40','kontrolwp')?>"><?=__('Length','kontrolwp')?> <?=(isset($data) && strpos($data, 'length:') !== FALSE) ? '('.substr($data, 7, strlen($data)).' '.__('characters','kontrolwp').')':'' ?></option>
        <option value="<?=(isset($data) && strpos($data, 'minLength:') !== FALSE) ? $data:'' ?>" <?=(isset($data) && strpos($data, 'minLength:') !== FALSE) ? 'selected="selected"':'' ?> class="custom-val" customValFormat="minLength:%s" customLabelFormat="<?=__('Min Length','kontrolwp')?> (%s <?=__('characters','kontrolwp')?>)" confirmText="<?=__('Enter the minimum character length for this field: eg. 40','kontrolwp')?>"><?=__('Min Length','kontrolwp')?> <?=(isset($data) && strpos($data, 'minLength:') !== FALSE) ? '('.substr($data, 10, strlen($data)).' '.__('characters','kontrolwp').')':'' ?></option>
        <option value="<?=(isset($data) && strpos($data, 'maxLength:') !== FALSE) ? $data:'' ?>" <?=(isset($data) && strpos($data, 'maxLength:') !== FALSE) ? 'selected="selected"':'' ?> class="custom-val" customValFormat="maxLength:%s" customLabelFormat="<?=__('Max Length','kontrolwp')?> (%s <?=__('characters','kontrolwp')?>)" confirmText="<?=__('Enter the maximum character length for this field: eg. 40','kontrolwp')?>"><?=__('Max Length','kontrolwp')?> <?=(isset($data) && strpos($data, 'maxLength:') !== FALSE) ? '('.substr($data, 10, strlen($data)).' '.__('characters','kontrolwp').')':'' ?></option>
        <option value="validate-currency-dollar" <?=(isset($data) && $data == 'validate-currency-dollar') ? 'selected="selected"':'' ?>><?=__('Currency (dollar format)','kontrolwp')?></option>
        <option value="validate-one-required" <?=(isset($data) && $data == 'validate-one-required') ? 'selected="selected"':'' ?>><?=__('One Required (eg. radio buttons)','kontrolwp')?></option>
      </select>
      <div class="inline duplicate-parent <?=isset($index) && ($index > 1) ? 'delete' : ''?>"></div>
</div>