 <div class="field">
      <select name="field[<?php echo $fkey?>][validation][]" class="sixty custom-select">
        <option value=""><?php echo __('None','kontrolwp')?></option>
        <option value="validate-email" <?php echo (isset($data) && $data == 'validate-email') ? 'selected="selected"':'' ?>><?php echo __('Email Address','kontrolwp')?></option>
        <option value="<?php echo (isset($data) && strpos($data, 'validate-date') !== FALSE) ? $data:'' ?>" <?php echo (isset($data) && strpos($data, 'validate-date') !== FALSE) ? 'selected="selected"':'' ?> class="custom-val" customValFormat="validate-date dateFormat:'%s'" customLabelFormat="<?php echo __('Date','kontrolwp')?> - '%s'" confirmText="<?php echo __('Enter the format of the date','kontrolwp')?>:" confirmDefaultVal="%d/%m/%Y"><?php echo __('Date','kontrolwp')?> <?php echo (isset($data) && strpos($data, 'validate-date') !== FALSE) ? '- '.substr($data, 25, strlen($data)):'' ?></option>
        <option value="validate-numeric" <?php echo (isset($data) && $data == 'validate-numeric') ? 'selected="selected"':'' ?>><?php echo __('Numeric','kontrolwp')?> (1, 1.1, -1 etc.)</option>
        <option value="validate-integer" <?php echo (isset($data) && $data == 'validate-integer') ? 'selected="selected"':'' ?>><?php echo __('Integer','kontrolwp')?> (1, 2, 3 etc.)</option>
        <option value="validate-digits" <?php echo (isset($data) && $data == 'validate-digits') ? 'selected="selected"':'' ?>><?php echo __('Digits (contains spaces, numbers eg. a phone number)','kontrolwp')?></option>
        <option value="validate-alpha" <?php echo (isset($data) && $data == 'validate-alpha') ? 'selected="selected"':'' ?>><?php echo __('Alpha (contains only letters)','kontrolwp')?></option>
        <option value="validate-alphanum" <?php echo (isset($data) && $data == 'validate-alphanum') ? 'selected="selected"':'' ?>><?php echo __('Alphanumeric (contains only letters and numbers)','kontrolwp')?></option>
        <option value="validate-url" <?php echo (isset($data) && $data == 'validate-url') ? 'selected="selected"':'' ?>><?php echo __('URL (url address','kontrolwp')?> eg. www.kontrolwp.com)</option>
        <option value="<?php echo (isset($data) && strpos($data, 'length:') !== FALSE) ? $data:'' ?>" <?php echo (isset($data) && strpos($data, 'length:') !== FALSE) ? 'selected="selected"':'' ?> class="custom-val" customValFormat="length:%s" customLabelFormat="<?php echo __('Length','kontrolwp')?> (%s <?php echo __('characters','kontrolwp')?>)" confirmText="<?php echo __('Enter the character length required for this field: eg. 40','kontrolwp')?>"><?php echo __('Length','kontrolwp')?> <?php echo (isset($data) && strpos($data, 'length:') !== FALSE) ? '('.substr($data, 7, strlen($data)).' '.__('characters','kontrolwp').')':'' ?></option>
        <option value="<?php echo (isset($data) && strpos($data, 'minLength:') !== FALSE) ? $data:'' ?>" <?php echo (isset($data) && strpos($data, 'minLength:') !== FALSE) ? 'selected="selected"':'' ?> class="custom-val" customValFormat="minLength:%s" customLabelFormat="<?php echo __('Min Length','kontrolwp')?> (%s <?php echo __('characters','kontrolwp')?>)" confirmText="<?php echo __('Enter the minimum character length for this field: eg. 40','kontrolwp')?>"><?php echo __('Min Length','kontrolwp')?> <?php echo (isset($data) && strpos($data, 'minLength:') !== FALSE) ? '('.substr($data, 10, strlen($data)).' '.__('characters','kontrolwp').')':'' ?></option>
        <option value="<?php echo (isset($data) && strpos($data, 'maxLength:') !== FALSE) ? $data:'' ?>" <?php echo (isset($data) && strpos($data, 'maxLength:') !== FALSE) ? 'selected="selected"':'' ?> class="custom-val" customValFormat="maxLength:%s" customLabelFormat="<?php echo __('Max Length','kontrolwp')?> (%s <?php echo __('characters','kontrolwp')?>)" confirmText="<?php echo __('Enter the maximum character length for this field: eg. 40','kontrolwp')?>"><?php echo __('Max Length','kontrolwp')?> <?php echo (isset($data) && strpos($data, 'maxLength:') !== FALSE) ? '('.substr($data, 10, strlen($data)).' '.__('characters','kontrolwp').')':'' ?></option>
        <option value="validate-currency-dollar" <?php echo (isset($data) && $data == 'validate-currency-dollar') ? 'selected="selected"':'' ?>><?php echo __('Currency (dollar format)','kontrolwp')?></option>
        <option value="validate-one-required" <?php echo (isset($data) && $data == 'validate-one-required') ? 'selected="selected"':'' ?>><?php echo __('One Required (eg. radio buttons)','kontrolwp')?></option>
      </select>
      <div class="inline duplicate-parent <?php echo isset($index) && ($index > 1) ? 'delete' : ''?>"></div>
</div>